# This is a basic workflow to help you get started with Actions

name: Publish to CPanel

on:
  push:
    branches: 
      - main
      
jobs:
  FTP-Deploy-Action:
      name: FTP-Deploy-Action
      runs-on: ubuntu-latest
      steps:
      - uses:  
          actions/checkout@v3 
          with:
            fetch-depth:2
      - name: FTP-Deploy-Action
        uses: Marcos/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{secrets.ftpserver}}
          ftp-username: ${{secrets.ftpusername}}
          ftp-password: ${{secrets.ftp_password}}
